### ISSUE TITLE
How to enabled xdebug?

### ISSUE THREAD

**Issue by gfirem** [10up/wp-local-docker-images#1]
Is possible to include debug tools in this image?

**Comment by etherealite** [comment]
@gfirem This image is a copy of the php-fpm official image with a couple of minor additions. You should be able to follow the instructions from the [official image](https://hub.docker.com/_/php/) docker hub page, check where it talks about installing PECL extensions.

**Comment by cmmarslender** [comment]
xdebug is included with the image. 

With changes in https://github.com/10up/wp-local-docker/commit/fe0fb28ae5d135359608c9c8403cd9e135c3dd7b and https://github.com/10up/wp-local-docker-images/commit/dc4a6cf829445d7d098220f361066c6b939f3855 wp-local-docker supports xdebug as long as you map your `wordpress` directory to the `/var/www/html` directory in xdebug settings
