### ISSUE TITLE
Alpine Linux, PHP-FPM and WordPress don't get along

### ISSUE THREAD

**Issue by etherealite** [10up/wp-local-docker-images#2]
Seeing if anyone has had any experience getting the official php:fpm-alpine [image ](https://hub.docker.com/_/php/)to work with wordpress. In my experience the PHP curl functions are not able to resolve DNS lookups, thus you commonly see messages in wp-admin exclaiming that wordpress was unable to check wordpress.org for updates.

I've search far and wide and not been able to find a solution. I figured if anyone knew it would be someone here.

**Comment by cmmarslender** [comment]
These images aren't based on alpine, so I don't think we'll have the solution. Sorry!
